[General]

## Background
Background="Backgrounds/bg-2.png"
DimBackgroundImage="0.7"
ScaleImageCropped="stretch"
ScreenWidth="1920"
ScreenHeight="1080"


## Blur
FullBlur="false"
PartialBlur="false"
BlurRadius="100"

## Design
FormBorderWidth="1"
FormBorderColor="#A3180B"
HaveFormBackground="true"
FormPosition="left"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"

MainColor="#FFFFFF"
AccentColor="#FFFFFF"
BackgroundColor="#000000"

OverrideLoginButtonTextColor="white"

InterfaceShadowSize="5"
InterfaceShadowOpacity="0.5"

RoundCorners="0"
ScreenPadding="0"

Font="JetBrainsMonoNL Nerd Font"
FontSize="10"

#------------------------------

## Interface Behavior

ForceRightToLeft="false"
ForceLastUser="false"
ForcePasswordFocus="false"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="true"

#------------------------------

## Locale Settings
Locale=""
HourFormat="hh:mm AP"
DateFormat="dddd, MMMM d"

## Translations
HeaderText="LET ME IN!!"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""
